import path from "node:path";
import { fileURLToPath } from "node:url";

const SRC_DIR = path.dirname(fileURLToPath(import.meta.url));

export const ROOT_DIR = path.resolve(SRC_DIR, "..");
export const CHALLENGES_DIR = path.join(ROOT_DIR, "challenges");
export const STATE_DIR = path.join(ROOT_DIR, ".flagdock");
export const STATE_PATH = path.join(STATE_DIR, "state.json");
export const DAEMON_PATH = path.join(STATE_DIR, "daemon.json");
export const LOG_PATH = path.join(STATE_DIR, "manager.log");
export const RUNTIME_DIR = path.join(STATE_DIR, "runtime");
export const PROMPTS_DIR = path.join(ROOT_DIR, "prompts");
export const COMMON_PROMPTS_DIR = path.join(PROMPTS_DIR, "common");
export const COMMON_CTF_PROMPT_FILE = path.join(COMMON_PROMPTS_DIR, "ctf.md");
export const SESSION_PROMPTS_DIR = path.join(PROMPTS_DIR, "sessions");
export const RUNTIME_AGENT_DIR = path.join(RUNTIME_DIR, "agent");
export const RUNTIME_OPENCODE_AGENT_FILE = path.join(RUNTIME_AGENT_DIR, "ctf.md");
export const RUNTIME_CODEX_DIR = path.join(RUNTIME_DIR, "codex");
export const RUNTIME_CODEX_AGENTS_FILE = path.join(RUNTIME_CODEX_DIR, "AGENTS.md");
export const LOCAL_DIR = path.join(ROOT_DIR, ".local");
export const LOCAL_OPENCODE_DIR = path.join(LOCAL_DIR, "opencode");
export const OPENCODE_CONFIG_FILE = path.join(LOCAL_OPENCODE_DIR, "opencode.json");
export const LEGACY_OPENCODE_CONFIG_FILE = path.join(ROOT_DIR, "opencode.json");
export const OPENCODE_AUTH_FILE = path.join(LOCAL_OPENCODE_DIR, "auth.json");
export const LOCAL_CODEX_DIR = path.join(LOCAL_DIR, "codex");
export const CODEX_CONFIG_FILE = path.join(LOCAL_CODEX_DIR, "config.toml");
export const CODEX_ENV_FILE = path.join(LOCAL_CODEX_DIR, "env");
export const FLAGDOCK_CONFIG_FILE = path.join(ROOT_DIR, "flagdock.yaml");
export const SOLUTIONS_DIR = path.join(STATE_DIR, "solutions");
export const WORKSPACES_DIR = path.join(STATE_DIR, "workspaces");
export const CONTAINER_CHALLENGE_DIR = "/challenge";
export const AGENT_NAME = "ctf";
export const BASE_IMAGE = "flagdock-sandbox-base:latest";
export const WORK_IMAGE = "flagdock-opencode:latest";
export const CODEX_IMAGE = "flagdock-codex:latest";
export const OPENCODE_PORT = 4096;
export const CODEX_PORT = 4097;
export const DEFAULT_MANAGER_HOST = "127.0.0.1";
export const BACKENDS = ["opencode", "codex"];
export const DEFAULT_BACKEND_MODE = "opencode";
export const SOLUTION_FLAG_FILE = "flag.txt";
export const SOLUTION_WRITEUP_FILE = "wp.md";
